/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-11 03:31:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.console.directory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class groupUserAssign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(16);
    _jspx_dependants.put("/WEB-INF/tags/commons/implicit.tld", Long.valueOf(1715136700000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/spring-webmvc-5.3.33.jar!/META-INF/spring.tld", Long.valueOf(1710407190000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/jsontable.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/tags/commons/popupFooter.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/tags/commons/popupHeader.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/msgEscHTML.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/implicit.tld", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/escape.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635287458000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/msgEscJS.tag", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/taglibs.jsp", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.33.jar", Long.valueOf(1713335440000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/spring-webmvc-5.3.33.jar!/META-INF/spring-form.tld", Long.valueOf(1710407190000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 response.setHeader("Cache-Control","no-cache, no-store"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html;charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_commons_005fpopupHeader_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"main-body-header\">\n");
      out.write("        ");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"main-body-content\">\n");
      out.write("        ");
      if (_jspx_meth_ui_005fjsontable_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(document).ready(function(){\n");
      out.write("            $('#JsonDataTable_searchTerm').hide();\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function assignUsers(selectedIds){\n");
      out.write("             if (confirm('");
      if (_jspx_meth_ui_005fmsgEscJS_005f0(_jspx_page_context))
        return;
      out.write("')) {\n");
      out.write("                UI.blockUI(); \n");
      out.write("                var callback = {\n");
      out.write("                    success : function() {\n");
      out.write("                        parent.location.reload(true);\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("                var request = ConnectionManager.post('");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("', callback, 'ids='+ selectedIds);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function closeDialog(dummy) {\n");
      out.write("            if (parent && parent.PopupDialog.closeDialog) {\n");
      out.write("                parent.PopupDialog.closeDialog();\n");
      out.write("            }\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      if (_jspx_meth_commons_005fpopupFooter_005f0(_jspx_page_context))
        return;
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_commons_005fpopupHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  commons:popupHeader
    org.apache.jsp.tag.web.commons.popupHeader_tag _jspx_th_commons_005fpopupHeader_005f0 = new org.apache.jsp.tag.web.commons.popupHeader_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_commons_005fpopupHeader_005f0);
    try {
      _jspx_th_commons_005fpopupHeader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_commons_005fpopupHeader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_commons_005fpopupHeader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(6,8) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("console.directory.group.user.assign.label.title");
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fjsontable_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:jsontable
    org.apache.jsp.tag.web.ui.jsontable_tag _jspx_th_ui_005fjsontable_005f0 = new org.apache.jsp.tag.web.ui.jsontable_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ui_005fjsontable_005f0);
    try {
      _jspx_th_ui_005fjsontable_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/web/json/directory/admin/user/notInGroup/list?groupId=${id}&${pageContext.request.queryString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = var type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setVar("JsonDataTable");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = divToUpdate type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setDivToUpdate("userList");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = jsonData type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setJsonData("data");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = rowsPerPage type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setRowsPerPage("15");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = width type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setWidth("100%");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = sort type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setSort("username");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = desc type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setDesc("false");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefParam type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefParam("id");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefQuery type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefQuery("false");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefDialog type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefDialog("false");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefDialogWidth type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefDialogWidth("600px");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefDialogHeight type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefDialogHeight("400px");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = hrefDialogTitle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setHrefDialogTitle("Process Dialog");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = checkbox type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setCheckbox("true");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "checkboxButton1", "console.directory.group.user.assign.label");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "checkboxCallback1", "assignUsers");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "checkboxButton2", "general.method.label.cancel");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "checkboxCallback2", "closeDialog");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = searchItems type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setSearchItems("name|Name");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) name = fields type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fjsontable_005f0.setFields("['id','username','firstName','lastName','email']");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "column1", "{key: 'username', label: 'console.directory.user.common.label.username', sortable: true}");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "column2", "{key: 'firstName', label: 'console.directory.user.common.label.firstName', sortable: true}");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "column3", "{key: 'lastName', label: 'console.directory.user.common.label.lastName', sortable: true}");
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(10,8) null
      _jspx_th_ui_005fjsontable_005f0.setDynamicAttribute(null, "column4", "{key: 'email', label: 'console.directory.user.common.label.email', sortable: true}");
      _jspx_th_ui_005fjsontable_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ui_005fjsontable_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ui_005fmsgEscJS_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ui:msgEscJS
    org.apache.jsp.tag.web.ui.msgEscJS_tag _jspx_th_ui_005fmsgEscJS_005f0 = new org.apache.jsp.tag.web.ui.msgEscJS_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_ui_005fmsgEscJS_005f0);
    try {
      _jspx_th_ui_005fmsgEscJS_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(44,26) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_ui_005fmsgEscJS_005f0.setKey("console.directory.group.user.assign.label.confirmation");
      _jspx_th_ui_005fmsgEscJS_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_ui_005fmsgEscJS_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/jsp/console/directory/groupUserAssign.jsp(51,54) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/web/console/directory/group/${id}/user/assign/submit", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_commons_005fpopupFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  commons:popupFooter
    org.apache.jsp.tag.web.commons.popupFooter_tag _jspx_th_commons_005fpopupFooter_005f0 = new org.apache.jsp.tag.web.commons.popupFooter_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_commons_005fpopupFooter_005f0);
    try {
      _jspx_th_commons_005fpopupFooter_005f0.setJspContext(_jspx_page_context);
      _jspx_th_commons_005fpopupFooter_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_commons_005fpopupFooter_005f0);
    }
    return false;
  }
}
