/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-12 03:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web.ui;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.joget.commons.util.TimeZoneUtil;
import org.joget.apps.app.service.AppUtil;

public final class dateToString_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/tags/commons/implicit.tld", Long.valueOf(1715136700000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/tags/ui/implicit.tld", Long.valueOf(1715136700000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/spring-webmvc-5.3.33.jar!/META-INF/spring.tld", Long.valueOf(1710407190000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1635287458000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153385082000L));
    _jspx_dependants.put("/WEB-INF/jsp/includes/taglibs.jsp", Long.valueOf(1715136700000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.33.jar", Long.valueOf(1713335440000L));
    _jspx_dependants.put("jar:file:/opt/joget-enterprise-linux-8.1.1/apache-tomcat-9.0.86/webapps/jw/WEB-INF/lib/spring-webmvc-5.3.33.jar!/META-INF/spring-form.tld", Long.valueOf(1710407190000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("org.joget.commons.util.TimeZoneUtil");
    _jspx_imports_classes.add("org.joget.apps.app.service.AppUtil");
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.util.Date date;
  private java.lang.String gmt;
  private java.lang.String format;

  public java.util.Date getDate() {
    return this.date;
  }

  public void setDate(java.util.Date date) {
    this.date = date;
    jspContext.setAttribute("date", date);
  }

  public java.lang.String getGmt() {
    return this.gmt;
  }

  public void setGmt(java.lang.String gmt) {
    this.gmt = gmt;
    jspContext.setAttribute("gmt", gmt);
  }

  public java.lang.String getFormat() {
    return this.format;
  }

  public void setFormat(java.lang.String format) {
    this.format = format;
    jspContext.setAttribute("format", format);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getDate() != null ) 
      _jspx_page_context.setAttribute("date", getDate());
    if( getGmt() != null ) 
      _jspx_page_context.setAttribute("gmt", getGmt());
    if( getFormat() != null ) 
      _jspx_page_context.setAttribute("format", getFormat());

    try {
 response.setHeader("Cache-Control","no-cache, no-store"); 
 response.setContentType("text/html;charset=UTF-8"); 
      out.print( TimeZoneUtil.convertToTimeZone(date, gmt, (format==null?AppUtil.getAppDateFormat():format)) );
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
